## install to ~/.k9s/views.yml
views:
  v1/pods:
    columns:
      - NAMESPACE
      - NAME
      - AGE
      - READY
      - RESTARTS
      - STATUS
      - CPU
      - MEM
      - "%CPU/R"
      - "%CPU/L"
      - "%MEM/R"
      - "%MEM/L"
      - IP
      - NODE
      - PF
